- name: config
  hosts: all
  become: true

  tasks:
    - name: update juicity server.json using jinja2
      template:
        src: server.json.j2
        dest: /etc/juicity/server.json

    - name: restart juicity systemd service
      action: systemd
      args:
        name: juicity-server
        state: restarted
