- name: install
  hosts: all
  become: true

  tasks:
    - name: download juicity.zip
      action: get_url
      args:
        url: https://github.com/juicity/juicity/releases/latest/download/juicity-linux-x86_64.zip
        dest: /tmp/juicity.zip

    - name: install unzip with package manager
      action: package
      args:
        name: unzip
        state: present

    - name: unzip juicity.zip
      action: unarchive
      args:
        remote_src: yes
        src: /tmp/juicity.zip
        dest: /tmp

    - name: copy binary
      action: copy
      args:
        mode: "755"
        remote_src: yes
        src: /tmp/juicity-server
        dest: /usr/bin/juicity-server

    - name: copy systemd service file
      action: copy
      args:
        remote_src: yes
        src: /tmp/juicity-server.service
        dest: /etc/systemd/system/juicity-server.service

    - name: create config directory
      action: file
      args:
        dest: /etc/juicity
        state: directory

    - name: enable systemd service
      action: systemd
      args:
        name: juicity-server
        daemon_reload: yes
        enabled: yes

    - name: check fullchain.cer
      action: stat
      args:
        path: /etc/juicity/fullchain.cer
      register: fullchain

    - name: check private.key
      action: stat
      args:
        path: /etc/juicity/private.key
      register: private

    - name: install lego with package manager
      action: package
      args:
        name: lego
        state: present

    - name: obtain certificates with lego
      action: command
      args:
        cmd: lego -a -m {{ letsencrypt_email }} -d {{ letsencrypt_hostname }} --path /etc/juicity --http run
      when: fullchain.stat.exists is false or private.stat.exists is false

    - name: link certificate - crt
      action: file
      args:
        state: link
        src: "/etc/juicity/certificates/{{ letsencrypt_hostname }}.crt"
        dest: /etc/juicity/fullchain.cer

    - name: link certificate - key
      action: file
      args:
        state: link
        src: "/etc/juicity/certificates/{{ letsencrypt_hostname }}.key"
        dest: /etc/juicity/private.key

    - name: install cron for certificate auto renewal
      action: package
      args:
        name: cron
        state: present

    - name: setup crontab for certificate auto renewal
      action: cron
      args:
        name: juicity-certificate-renewal
        job: lego -a -m {{ letsencrypt_email }} -d {{ letsencrypt_hostname }} --path /etc/juicity --http renew
        month: 1
